### ISSUE TITLE
Move Hook librarys to Lua

### ISSUE THREAD

**Issue by GlorifiedPig** [GlorifiedPig/VRBox#10]
## Description
No reason for it to be on C#, would make it way more accessible.

**Comment by artemking4** [comment]
There is a reason. Hooks do need to be called from C#, and they need to be there, otherwise, if u just call them from C# as regular fields, they may get hooked, it would lead to bad things.

**Comment by GlorifiedPig** [comment]
> 
> 
> There is a reason. Hooks do need to be called from C#, and they need to be there, otherwise, if u just call them from C# as regular fields, they may get hooked, it would lead to bad things.

can be detoured anyway whether it's in C# or not though

**Comment by GlorifiedPig** [comment]
Implemented in commit https://github.com/GlorifiedPig/VRBox/commit/c3dcd68e00e67038f598cdc93d4f17127b1777f0.
